# Generated by Django 3.1.2 on 2020-10-03 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appeals', '0002_auto_20201003_1904'),
    ]

    operations = [
        migrations.AddField(
            model_name='appeal',
            name='fio',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appeal',
            name='reason',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
