# Generated by Django 3.1.2 on 2020-10-03 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appeals', '0003_auto_20201003_1931'),
    ]

    operations = [
        migrations.AddField(
            model_name='appeal',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
